import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.css";
// import Navbar from "./components/Navbar/Navbar";
// import Footer from "./components/Footer/Footer";
import CommingSoon from "./components/CommingSoon/CommingSoon";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["900"],
  variable: "--font-montserrat",
  display: "swap",
});

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
//   display: "swap",
// });

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway",
  display: "swap",
});

// const panameraLight = localFont({
//   src: "./fonts/Panamera-Light.otf",
//   variable: "--font-panamera-light",
// });

// const panameraRegular = localFont({
//   src: "./fonts/Panamera-Regular.otf",
//   variable: "--font-panamera-regular",
// });

// const panameraMedium = localFont({
//   src: "./fonts/Panamera-Medium.otf",
//   variable: "--font-panamera-medium",
// });

// const panameraBold = localFont({
//   src: "./fonts/Panamera-Bold.otf",
//   variable: "--font-panamera-bold",
// });

export const metadata: Metadata = {
  title: "Venn Studio | Comming Soon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${panameraLight.variable} ${panameraRegular.variable} ${panameraMedium.variable} ${panameraBold.variable} ${montserrat.variable} ${poppins.variable} antialiased flex flex-col items-stretch min-h-screen bg-neutralLight-100 relative`}
        // className={`${poppins.variable} antialiased flex flex-col items-stretch min-h-screen bg-neutralLight-100 relative`}
        className={`${raleway.variable} ${montserrat.variable} font-[family-name:var(--font-raleway)] antialiased flex flex-col items-stretch min-h-screen bg-neutralLight-100 relative`}
        // className={`${panameraRegular.className} antialiased`}
      >
        {/* <Navbar />
        {children}
        <Footer /> */}
        <CommingSoon/>
        {/* <div className="absolute top-0 left-0 z-[-1] h-full w-full overflow-hidden blur-[30px]">
          <Image
            // className="rotate-180 opacity-60"
            className="rotate-90 opacity-50"
            src="images/circles-desktop7.svg"
            alt="About us"
            width={1440}
            height={800}
            priority
          />
        </div> */}
      </body>
    </html>
  );
}
